version: '3.9'
services:
    dev-db:
        image: mysql:8
        ports:
            - 3306:3306
        environment:
            MYSQL_ROOT_PASSWORD: rootpassword
            MYSQL_DATABASE: dev_db
            MYSQL_USER: dev_user
            MYSQL_PASSWORD: dev123
        volumes:
            - dev-db-data:/var/lib/mysql

    test-db:
        image: mysql:8
        ports:
            - 3307:3306
        environment:
            MYSQL_ROOT_PASSWORD: rootpassword
            MYSQL_DATABASE: test_db
            MYSQL_USER: test_user
            MYSQL_PASSWORD: testpassword
        volumes:
            - test-db-data:/var/lib/mysql

volumes:
    dev-db-data:
    test-db-data:
