version: '3.9'
services:
    dev-db:
        image: mysql:8.0.36
        ports:
            - 3306:3306
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: CNPM_smartprint
            MYSQL_USER: devUser
            MYSQL_PASSWORD: devPassword
        volumes:
            - dev-db-data:/var/lib/mysql

volumes:
    dev-db-data:
